plugins {
    id 'java-library'
}

repositories {
    mavenCentral()
}

dependencies {
            testImplementation 'io.rest-assured:rest-assured:5.4.0'
            testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.1'
            testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.1'
            testImplementation 'com.fasterxml.jackson.core:jackson-databind:2.16.1'

}

tasks.withType(Test) {
    useJUnitPlatform()

    testLogging {
        lifecycle {
            events "started", "skipped", "failed", "standard_error", "standard_out"
            exceptionFormat "short"
        }
    }

}

test {
    useJUnitPlatform()
}
